"""Tests for services/chat/tools.py's execute_tool dispatcher — the part
that actually enforces "the LLM handles conversation only; all real
numbers come from our actual backend functions, never generated by the
model". Each test proves a given tool call reaches the *real* backend
function (the same one the HTTP routes use) and returns *real* data, not
something invented for the chat path.
"""

from __future__ import annotations

import json
import uuid
from datetime import datetime, timezone

import pytest
from sqlalchemy import select, text

import app.services.analytics.weekly as weekly_mod
import app.services.glucose.manual_log_service as manual_log_module
from app.models.glucose_reading import GlucoseReadingModel
from app.models.health_metric import HealthMetric
from app.models.ifct_food import IFCTFood
from app.models.meal_log import MealLog
from app.services.chat.tools import TOOL_SCHEMAS, execute_tool

from .conftest import build_sqlite_db, build_sqlite_timescale_db, make_user


@pytest.fixture
async def db_and_user():
    engine, session_factory = await build_sqlite_db()
    ts_engine, ts_session_factory = await build_sqlite_timescale_db()

    original_weekly_ts = weekly_mod.TimescaleSessionLocal
    weekly_mod.TimescaleSessionLocal = ts_session_factory
    original_manual_log_ts = manual_log_module.TimescaleSessionLocal
    manual_log_module.TimescaleSessionLocal = ts_session_factory

    user = await make_user(session_factory, "chat@example.com")

    async with session_factory() as session:
        # A small IFCT seed so log_meal/get_meals/get_daily_nutrition tests
        # resolve locally (source="ifct") instead of falling through to a
        # real network call against USDA/Gemini — this suite runs fully
        # offline, same convention as the rest of the backend tests.
        session.add_all([
            IFCTFood(id=uuid.uuid4(), code="A015", name="Rice, raw, milled",
                      energy_kcal=356.4, available_carb_g=78.24, protein_g=7.94,
                      fat_g=0.52, fibre_g=2.81, sugars_g=0.69),
            IFCTFood(id=uuid.uuid4(), code="D001", name="dal",
                      energy_kcal=120.0, available_carb_g=20.0, protein_g=7.0,
                      fat_g=0.5, fibre_g=4.0, sugars_g=1.0),
            IFCTFood(id=uuid.uuid4(), code="F001", name="banana",
                      energy_kcal=90.0, available_carb_g=22.0, protein_g=1.2,
                      fat_g=0.2, fibre_g=1.1, sugars_g=15.0),
        ])
        await session.commit()

        yield session, user, ts_session_factory

    weekly_mod.TimescaleSessionLocal = original_weekly_ts
    manual_log_module.TimescaleSessionLocal = original_manual_log_ts
    await engine.dispose()
    await ts_engine.dispose()


# ── Structural safety guarantee ──────────────────────────────────────────

def test_no_dosing_or_medication_tool_exists_at_all():
    """The core structural guarantee, independent of the system prompt:
    there is no tool the model could call that would ever return an
    insulin dose or medication amount. Not "the tool refuses" — the tool
    doesn't exist."""
    names = {schema["function"]["name"] for schema in TOOL_SCHEMAS}
    for forbidden in ("dose", "dosage", "insulin", "medication", "medicine"):
        assert not any(forbidden in name.lower() for name in names), (
            f"found a tool name containing {forbidden!r}: {names}"
        )


async def test_unknown_tool_name_is_a_soft_error_not_a_crash(db_and_user):
    db, user, _ts = db_and_user
    result = await execute_tool("compute_insulin_dose", {}, db, user)
    assert "error" in result


# ── get_glucose_analytics ────────────────────────────────────────────────

async def test_get_glucose_analytics_reports_real_readings(db_and_user):
    db, user, ts_session_factory = db_and_user
    now = datetime.now(timezone.utc)
    async with ts_session_factory() as ts:
        ts.add(GlucoseReadingModel(id=uuid.uuid4(), user_id=user.id, value_mgdl=120, recorded_at=now, source="MANUAL"))
        ts.add(GlucoseReadingModel(id=uuid.uuid4(), user_id=user.id, value_mgdl=160, recorded_at=now, source="MANUAL"))
        await ts.commit()

    result = await execute_tool("get_glucose_analytics", {"days": 7}, db, user)

    assert result["has_data"] is True
    assert result["average_mgdl"] == 140.0
    assert result["reading_count"] == 2


async def test_get_glucose_analytics_no_data_is_honest(db_and_user):
    db, user, _ts = db_and_user
    result = await execute_tool("get_glucose_analytics", {}, db, user)
    assert result["has_data"] is False


# ── get_health_trends / get_water_daily ──────────────────────────────────

async def test_get_health_trends_reports_real_steps(db_and_user):
    db, user, _ts = db_and_user
    now = datetime.now(timezone.utc)
    db.add(HealthMetric(user_id=user.id, metric="steps", value=7500, unit="count", started_at=now, ended_at=now, source="APPLE_HEALTH"))
    await db.commit()

    result = await execute_tool("get_health_trends", {"days": 7}, db, user)
    assert result["steps"]["has_data"] is True
    assert result["steps"]["daily"][-1]["value"] == 7500


async def test_get_water_daily_is_null_with_nothing_logged(db_and_user):
    db, user, _ts = db_and_user
    result = await execute_tool("get_water_daily", {}, db, user)
    assert result["total_ml"] is None
    assert result["goal_ml"] == 2000


# ── log_water ─────────────────────────────────────────────────────────────

async def test_log_water_a_glass_persists_a_real_health_metric(db_and_user):
    db, user, _ts = db_and_user
    result = await execute_tool("log_water", {"amount_ml": 250}, db, user)
    assert result["logged_ml"] == 250
    assert result["total_ml_today"] == 250

    daily = await execute_tool("get_water_daily", {}, db, user)
    assert daily["total_ml"] == 250


async def test_log_water_rejects_a_non_positive_amount(db_and_user):
    db, user, _ts = db_and_user
    result = await execute_tool("log_water", {"amount_ml": 0}, db, user)
    assert "error" in result


# ── log_manual_glucose ────────────────────────────────────────────────────

async def test_log_manual_glucose_persists_a_real_reading(db_and_user):
    db, user, ts_session_factory = db_and_user

    result = await execute_tool("log_manual_glucose", {"value_mgdl": 145}, db, user)
    assert result["value_mgdl"] == 145
    assert result["reading_id"]

    async with ts_session_factory() as ts:
        rows = (await ts.execute(
            select(GlucoseReadingModel).where(GlucoseReadingModel.user_id == user.id)
        )).scalars().all()
    assert len(rows) == 1
    assert rows[0].value_mgdl == 145
    assert rows[0].source == "MANUAL"


async def test_log_manual_glucose_rejects_out_of_range_value(db_and_user):
    db, user, _ts = db_and_user
    result = await execute_tool("log_manual_glucose", {"value_mgdl": 900}, db, user)
    assert "error" in result


# ── log_meal (real IFCT/USDA/Gemini source router) ───────────────────────

async def test_log_meal_resolves_via_ifct_for_a_known_ingredient(db_and_user):
    db, user, _ts = db_and_user

    result = await execute_tool(
        "log_meal", {"food_name": "Rice, raw, milled", "portion_grams": 100}, db, user,
    )

    assert result["nutrition_source"] == "ifct"
    assert result["nutrition_verified"] is True
    assert result["carbs_g"] == pytest.approx(78.24, abs=0.1)
    assert result["meal_id"]

    meals = (await db.execute(select(MealLog).where(MealLog.user_id == user.id))).scalars().all()
    assert len(meals) == 1


async def test_get_meals_lists_what_was_just_logged(db_and_user):
    db, user, _ts = db_and_user
    await execute_tool("log_meal", {"food_name": "dal", "portion_grams": 150}, db, user)

    result = await execute_tool("get_meals", {"days": 7}, db, user)
    assert result["count"] == 1
    assert result["meals"][0]["name"].lower() == "dal"


async def test_get_daily_nutrition_reflects_a_logged_meal(db_and_user):
    db, user, _ts = db_and_user

    # daily_nutrition_totals reads via raw SQL (services/nutrition/
    # meals_today.py — JSONB has no sqlite compiler, same as elsewhere in
    # this app), which on sqlite expects a dashed UUID string; the ORM
    # write path log_meal goes through stores the hex form instead (its
    # bind processor's own convention). The two are consistent with each
    # other on real Postgres (native uuid comparison doesn't care about
    # formatting) but not on sqlite, so this test seeds the meal directly
    # in the representation the raw-SQL reader expects, rather than
    # chaining through log_meal first — see
    # tests/test_dashboard_activity_zero_fill.py for the same pattern.
    await db.execute(
        text("""
            INSERT INTO meal_logs (id, user_id, meal_time, food_items, total_calories, total_carbs_g)
            VALUES (:id, :user_id, :meal_time, :food_items, :calories, :carbs_g)
        """),
        {
            "id": str(uuid.uuid4()), "user_id": str(user.id), "meal_time": datetime.now(timezone.utc),
            "food_items": json.dumps([{"name": "banana"}]), "calories": 90, "carbs_g": 22.0,
        },
    )
    await db.commit()

    result = await execute_tool("get_daily_nutrition", {}, db, user)
    assert result["meal_count"] == 1
    assert result["consumed_kcal"] == 90
