"""
Doctor report generation.

The frontend kicks off generation, polls for status, then receives a
`download_url`. Generation is fast and done inline here, but the job-based
contract is kept so it can move to a background worker (Celery) later without a
frontend change.

Reports are produced as self-contained HTML (printable to PDF from any browser).
Swap `_build_report_html` for a real PDF renderer (reportlab / weasyprint) when
that dependency is acceptable.
"""

import html
import uuid
from datetime import datetime, timezone

from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import HTMLResponse
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from ..database import get_db
from ..models.user import User, InsulinProfile
from .auth import get_current_user, get_verified_user

router = APIRouter()

# In-memory job store keyed by job_id. Reports are ephemeral; for multi-instance
# deployments move this to Postgres or object storage.
_jobs: dict = {}


@router.post("/reports/generate")
async def generate_report(
    current_user: User = Depends(get_verified_user),
    db: AsyncSession = Depends(get_db),
):
    job_id = str(uuid.uuid4())
    _jobs[job_id] = {
        "status": "PROCESSING",
        "user_id": str(current_user.id),
        "html": None,
        "created_at": datetime.now(timezone.utc),
    }
    try:
        _jobs[job_id]["html"] = await _build_report_html(current_user, db)
        _jobs[job_id]["status"] = "COMPLETED"
    except Exception:
        _jobs[job_id]["status"] = "FAILED"

    return {"job_id": job_id, "status": _jobs[job_id]["status"]}


@router.get("/reports/{job_id}/status")
async def report_status(
    job_id: str,
    current_user: User = Depends(get_current_user),
):
    job = _jobs.get(job_id)
    if not job or job["user_id"] != str(current_user.id):
        raise HTTPException(status_code=404, detail="Report not found")

    response = {"status": job["status"]}
    if job["status"] == "COMPLETED":
        response["download_url"] = f"/api/v1/reports/{job_id}/download"
    return response


@router.get("/reports/{job_id}/download", response_class=HTMLResponse)
async def download_report(
    job_id: str,
    current_user: User = Depends(get_current_user),
):
    job = _jobs.get(job_id)
    if not job or job["user_id"] != str(current_user.id) or job["status"] != "COMPLETED":
        raise HTTPException(status_code=404, detail="Report not available")
    return HTMLResponse(content=job["html"])


# ── Report rendering ──────────────────────────────────────────────────────────

async def _build_report_html(user: User, db: AsyncSession) -> str:
    result = await db.execute(
        select(InsulinProfile).where(InsulinProfile.user_id == user.id)
    )
    profile = result.scalars().first()

    def esc(value) -> str:
        return html.escape(str(value)) if value is not None else "—"

    generated = datetime.now(timezone.utc).strftime("%d %b %Y, %H:%M UTC")

    insulin_rows = ""
    if profile is not None:
        insulin_rows = f"""
          <tr><td>Insulin-to-carb ratio (ICR)</td><td>{esc(profile.icr)}</td></tr>
          <tr><td>Insulin sensitivity factor (ISF)</td><td>{esc(profile.isf)}</td></tr>
          <tr><td>Basal rate</td><td>{esc(profile.basal_rate)}</td></tr>
          <tr><td>Target glucose</td><td>{esc(profile.target_glucose_min)}–{esc(profile.target_glucose_max)} mg/dL</td></tr>
          <tr><td>Insulin type</td><td>{esc(profile.insulin_type)}</td></tr>
        """
    else:
        insulin_rows = '<tr><td colspan="2">No insulin profile on file.</td></tr>'

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Mytr.AI — Doctor Report</title>
  <style>
    body {{ font-family: -apple-system, Segoe UI, Roboto, sans-serif; color: #1a1a1a; margin: 40px; }}
    h1 {{ font-size: 22px; margin-bottom: 4px; }}
    .muted {{ color: #777; font-size: 13px; }}
    table {{ border-collapse: collapse; width: 100%; margin-top: 16px; }}
    td {{ border: 1px solid #e0e0e0; padding: 8px 12px; font-size: 14px; }}
    td:first-child {{ color: #555; width: 55%; }}
    h2 {{ font-size: 15px; margin-top: 28px; text-transform: uppercase; letter-spacing: 0.5px; color: #6DC534; }}
  </style>
</head>
<body>
  <h1>Doctor Report</h1>
  <div class="muted">Generated {generated}</div>

  <h2>Patient</h2>
  <table>
    <tr><td>Name</td><td>{esc(user.name)}</td></tr>
    <tr><td>Email</td><td>{esc(user.email)}</td></tr>
    <tr><td>Date of birth</td><td>{esc(user.dob)}</td></tr>
    <tr><td>Gender</td><td>{esc(user.gender)}</td></tr>
    <tr><td>Diabetes type</td><td>{esc(user.diabetes_type)}</td></tr>
  </table>

  <h2>Insulin Profile</h2>
  <table>{insulin_rows}</table>

  <p class="muted" style="margin-top:32px">
    This report was generated by Mytr.AI and is intended to support, not replace,
    clinical judgement.
  </p>
</body>
</html>"""
