"""Conversation orchestration for the analytics chatbot: builds the
system prompt + message list, runs the tool-call loop against Groq, logs
every turn. This is what actually enforces the "the LLM handles
conversation only; all real numbers come from our actual backend
functions, never generated by the model" design principle —
groq_service.py is a dumb HTTP client and tools.py just executes what
it's told; this module is what makes sure a real tool call happens
before any tool-result-derived number reaches the user, by construction
(the model literally cannot get a number into its final reply without a
tool result appearing in the message list first — there is nowhere else
in the protocol for it to come from).
"""

from __future__ import annotations

import json
import os
import uuid
from typing import Any, Optional

from sqlalchemy.ext.asyncio import AsyncSession

from ...models.user import User
from ..groq_service import GroqService
from . import log as chat_log
from .tools import TOOL_SCHEMAS, execute_tool

SYSTEM_PROMPT = """You are Mytr.AI's analytics assistant. You help users understand their own logged health data (glucose, meals, activity, sleep, water) and log new entries when they mention eating, drinking, or a glucose reading.

STRICT RULES — never broken, no exceptions for how the question is framed:
1. Every number you state (glucose values, calories, carbs, steps, percentages, amounts, dates — anything numeric) must come from a tool call you made in this same conversation. Never state a number from memory or estimation. If you don't have a tool result for it, call the right tool first.
2. You have no tool to compute insulin doses or any medication amount, and you must never state, suggest, estimate, or imply one — even if asked directly, asked to "just estimate", or asked hypothetically. Always say dosing and medication decisions must come from their doctor or diabetes care team, and that you can only show their own data.
3. Never give a personalized medical or treatment directive ("you should...", "increase your...", "stop taking..."). General, non-personalized educational information is fine (e.g. "carbohydrates generally raise blood glucose").
4. Any question really about diagnosis, treatment, dosing, or medication: say clearly this is for their clinician, and stop there.
5. When the user mentions eating something, drinking water, or a glucose reading, actually call the matching log tool — don't just acknowledge it in text, that doesn't save it.
6. Be concise and conversational. State real numbers in plain language, not a raw data dump."""

# Guards against a runaway tool-call loop (a misbehaving model calling
# tools indefinitely without ever settling on an answer) — not a
# normal-use limit. A real question resolves in 1-2 tool calls.
_MAX_TOOL_ITERATIONS = 4


def _build_groq_service() -> GroqService:
    return GroqService(api_key=os.getenv("GROQ_API_KEY", ""))


async def run_conversation(
    db: AsyncSession,
    user: User,
    message: str,
    history: list[dict[str, str]],
    conversation_id: Optional[str] = None,
    groq: Optional[GroqService] = None,
) -> dict[str, Any]:
    """Runs one user turn to completion: sends the message (+ history) to
    Groq, executes any tool calls it asks for against real data, feeds
    the real results back, repeats until the model responds with plain
    text (or _MAX_TOOL_ITERATIONS is hit). Logs every turn.

    `groq` is injectable for tests; production callers omit it and get a
    real GroqService reading GROQ_API_KEY from the environment.
    """
    groq = groq or _build_groq_service()
    conversation_id = conversation_id or str(uuid.uuid4())

    messages: list[dict[str, Any]] = [{"role": "system", "content": SYSTEM_PROMPT}]
    for turn in history:
        messages.append({"role": turn["role"], "content": turn["content"]})
    messages.append({"role": "user", "content": message})

    await chat_log.log_turn(db, user.id, conversation_id, "user", content=message)

    tools_used: list[str] = []
    for _ in range(_MAX_TOOL_ITERATIONS):
        reply = await groq.chat(messages, tools=TOOL_SCHEMAS)

        if not reply.wants_tool_call:
            final_text = reply.content or ""
            await chat_log.log_turn(db, user.id, conversation_id, "assistant", content=final_text)
            return {"reply": final_text, "conversation_id": conversation_id, "tools_used": tools_used}

        # Groq's protocol (OpenAI-compatible) expects the assistant's own
        # tool-call message echoed back before the tool results.
        messages.append({
            "role": "assistant",
            "content": reply.content,
            "tool_calls": [
                {
                    "id": call.id,
                    "type": "function",
                    "function": {"name": call.name, "arguments": json.dumps(call.arguments)},
                }
                for call in reply.tool_calls
            ],
        })

        for call in reply.tool_calls:
            result = await execute_tool(call.name, call.arguments, db, user)
            tools_used.append(call.name)
            await chat_log.log_turn(
                db, user.id, conversation_id, "tool",
                tool_name=call.name, tool_arguments=call.arguments, tool_result=result,
            )
            messages.append({
                "role": "tool",
                "tool_call_id": call.id,
                "content": json.dumps(result),
            })

    # Hit the iteration cap without the model settling on a final answer —
    # fail honestly rather than silently returning nothing (or worse,
    # returning text from a turn that never got its tool result folded in).
    fallback = "I wasn't able to finish looking that up — please try asking again."
    await chat_log.log_turn(db, user.id, conversation_id, "assistant", content=fallback)
    return {"reply": fallback, "conversation_id": conversation_id, "tools_used": tools_used}
